In [8]:
import pandas as pd

In [3]:
pip install ucimlrepo

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: ucimlrepo in c:\users\thy\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (0.0.7)
Requirement already satisfied: pandas>=1.0.0 in c:\users\thy\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from ucimlrepo) (2.2.3)
Requirement already satisfied: certifi>=2020.12.5 in c:\users\thy\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from ucimlrepo) (2025.4.26)
Requirement already satisfied: numpy>=1.26.0 in c:\users\thy\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas>=1.0.0->ucimlrepo) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\thy\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas>=1.0.0->ucimlrepo) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\thy\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas>=1.0.0->ucimlrepo) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\thy\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas>=1.0.0->ucimlrepo) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\thy\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ucimlrepo) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: C:\Users\Thy\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [5]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
automobile = fetch_ucirepo(id=10) 
  
# data (as pandas dataframes) 
X = automobile.data.features 
y = automobile.data.targets 
  
# metadata 
print(automobile.metadata) 
  
# variable information 
print(automobile.variables)

{'uci_id': 10, 'name': 'Automobile', 'repository_url': 'https://archive.ics.uci.edu/dataset/10/automobile', 'data_url': 'https://archive.ics.uci.edu/static/public/10/data.csv', 'abstract': "From 1985 Ward's Automotive Yearbook", 'area': 'Other', 'tasks': ['Regression'], 'characteristics': ['Multivariate'], 'num_instances': 205, 'num_features': 25, 'feature_types': ['Categorical', 'Integer', 'Real'], 'demographics': [], 'target_col': ['symboling'], 'index_col': None, 'has_missing_values': 'yes', 'missing_values_symbol': 'NaN', 'year_of_dataset_creation': 1985, 'last_updated': 'Thu Aug 10 2023', 'dataset_doi': '10.24432/C5B01C', 'creators': ['Jeffrey Schlimmer'], 'intro_paper': None, 'additional_info': {'summary': 'This data set consists of three types of entities: (a) the specification of an auto in terms of various characteristics, (b) its assigned insurance risk rating, (c) its normalized losses in use as compared to other cars.  The second rating corresponds to the degree to which the auto is more risky than its price indicates. Cars are initially assigned a risk factor symbol associated with its price.   Then, if it is more risky (or less), this symbol is adjusted by moving it up (or down) the scale.  Actuarians call this process "symboling".  A value of +3 indicates that the auto is risky, -3 that it is probably pretty safe.\r\n\r\nThe third factor is the relative average loss payment per insured vehicle year.  This value is normalized for all autos within a particular size classification (two-door small, station wagons, sports/speciality, etc...), and represents the average loss per car per year.\r\n\r\nNote: Several of the attributes in the database could be used as a "class" attribute.', 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': 'Attribute: Attribute Range\r\n\r\n  1. symboling:                -3, -2, -1, 0, 1, 2, 3.\r\n  2. normalized-losses:        continuous from 65 to 256.\r\n  3. make:                     \r\n                               alfa-romero, audi, bmw, chevrolet, dodge, honda,\r\n                               isuzu, jaguar, mazda, mercedes-benz, mercury,\r\n                               mitsubishi, nissan, peugot, plymouth, porsche,\r\n                               renault, saab, subaru, toyota, volkswagen, volvo\r\n\r\n  4. fuel-type:                diesel, gas.\r\n  5. aspiration:               std, turbo.\r\n  6. num-of-doors:             four, two.\r\n  7. body-style:               hardtop, wagon, sedan, hatchback, convertible.\r\n  8. drive-wheels:             4wd, fwd, rwd.\r\n  9. engine-location:          front, rear.\r\n 10. wheel-base:               continuous from 86.6 120.9.\r\n 11. length:                   continuous from 141.1 to 208.1.\r\n 12. width:                    continuous from 60.3 to 72.3.\r\n 13. height:                   continuous from 47.8 to 59.8.\r\n 14. curb-weight:              continuous from 1488 to 4066.\r\n 15. engine-type:              dohc, dohcv, l, ohc, ohcf, ohcv, rotor.\r\n 16. num-of-cylinders:         eight, five, four, six, three, twelve, two.\r\n 17. engine-size:              continuous from 61 to 326.\r\n 18. fuel-system:              1bbl, 2bbl, 4bbl, idi, mfi, mpfi, spdi, spfi.\r\n 19. bore:                     continuous from 2.54 to 3.94.\r\n 20. stroke:                   continuous from 2.07 to 4.17.\r\n 21. compression-ratio:        continuous from 7 to 23.\r\n 22. horsepower:               continuous from 48 to 288.\r\n 23. peak-rpm:                 continuous from 4150 to 6600.\r\n 24. city-mpg:                 continuous from 13 to 49.\r\n 25. highway-mpg:              continuous from 16 to 54.\r\n 26. price:                    continuous from 5118 to 45400.', 'citation': None}}
                 name     role         type demographic  \
0               price  Feature   Continuous        None
1         highway-mpg  Feature   Continuous        None
2            city-mpg  Feature   Continuous        None
3            peak-rpm  Feature   Continuous        None
4          horsepower  Feature   Continuous        None
5   compression-ratio  Feature   Continuous        None
6              stroke  Feature   Continuous        None
7                bore  Feature   Continuous        None
8         fuel-system  Feature  Categorical        None
9         engine-size  Feature   Continuous        None
10   num-of-cylinders  Feature      Integer        None
11        engine-type  Feature  Categorical        None
12        curb-weight  Feature   Continuous        None
13             height  Feature   Continuous        None
14              width  Feature   Continuous        None
15             length  Feature   Continuous        None
16         wheel-base  Feature   Continuous        None
17    engine-location  Feature       Binary        None
18       drive-wheels  Feature  Categorical        None
19         body-style  Feature  Categorical        None
20       num-of-doors  Feature      Integer        None
21         aspiration  Feature       Binary        None
22          fuel-type  Feature       Binary        None
23               make  Feature  Categorical        None
24  normalized-losses  Feature   Continuous        None
25          symboling   Target      Integer        None

                                          description units missing_values
0                       continuous from 5118 to 45400  None            yes
1                            continuous from 16 to 54  None             no
2                            continuous from 13 to 49  None             no
3                        continuous from 4150 to 6600  None            yes
4                           continuous from 48 to 288  None            yes
5                             continuous from 7 to 23  None             no
6                        continuous from 2.07 to 4.17  None            yes
7                        continuous from 2.54 to 3.94  None            yes
8        1bbl, 2bbl, 4bbl, idi, mfi, mpfi, spdi, spfi  None             no
9                           continuous from 61 to 326  None             no
10         eight, five, four, six, three, twelve, two  None             no
11             dohc, dohcv, l, ohc, ohcf, ohcv, rotor  None             no
12                       continuous from 1488 to 4066  None             no
13                       continuous from 47.8 to 59.8  None             no
14                       continuous from 60.3 to 72.3  None             no
15                     continuous from 141.1 to 208.1  None             no
16                         continuous from 86.6 120.9  None             no
17                                        front, rear  None             no
18                                      4wd, fwd, rwd  None             no
19      hardtop, wagon, sedan, hatchback, convertible  None             no
20                                          four, two  None            yes
21                                         std, turbo  None             no
22                                        diesel, gas  None             no
23  alfa-romero, audi, bmw, chevrolet, dodge, hond...  None             no
24                          continuous from 65 to 256  None            yes
25                             -3, -2, -1, 0, 1, 2, 3  None             no

In [9]:
df = pd.read_csv('https://archive.ics.uci.edu/static/public/10/data.csv')

#### Xử lý dữ liệu khuyết

In [10]:
df

,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,...,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,symboling
0,NaN,alfa-romero,gas,std,2.0,convertible,rwd,front,88.6,168.8,...,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0,3
1,NaN,alfa-romero,gas,std,2.0,convertible,rwd,front,88.6,168.8,...,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0,3
2,NaN,alfa-romero,gas,std,2.0,hatchback,rwd,front,94.5,171.2,...,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0,1
3,164.0,audi,gas,std,4.0,sedan,fwd,front,99.8,176.6,...,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0,2
4,164.0,audi,gas,std,4.0,sedan,4wd,front,99.4,176.6,...,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,95.0,volvo,gas,std,4.0,sedan,rwd,front,109.1,188.8,...,mpfi,3.78,3.15,9.5,114.0,5400.0,23,28,16845.0,-1
201,95.0,volvo,gas,turbo,4.0,sedan,rwd,front,109.1,188.8,...,mpfi,3.78,3.15,8.7,160.0,5300.0,19,25,19045.0,-1
202,95.0,volvo,gas,std,4.0,sedan,rwd,front,109.1,188.8,...,mpfi,3.58,2.87,8.8,134.0,5500.0,18,23,21485.0,-1
203,95.0,volvo,diesel,turbo,4.0,sedan,rwd,front,109.1,188.8,...,idi,3.01,3.40,23.0,106.0,4800.0,26,27,22470.0,-1
204,95.0,volvo,gas,turbo,4.0,sedan,rwd,front,109.1,188.8,...,mpfi,3.78,3.15,9.5,114.0,5400.0,19,25,22625.0,-1

In [13]:
df = df.replace(['?', 'NaN'], pd.NA)
df

,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,...,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,symboling
0,NaN,alfa-romero,gas,std,2.0,convertible,rwd,front,88.6,168.8,...,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0,3
1,NaN,alfa-romero,gas,std,2.0,convertible,rwd,front,88.6,168.8,...,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0,3
2,NaN,alfa-romero,gas,std,2.0,hatchback,rwd,front,94.5,171.2,...,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0,1
3,164.0,audi,gas,std,4.0,sedan,fwd,front,99.8,176.6,...,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0,2
4,164.0,audi,gas,std,4.0,sedan,4wd,front,99.4,176.6,...,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,95.0,volvo,gas,std,4.0,sedan,rwd,front,109.1,188.8,...,mpfi,3.78,3.15,9.5,114.0,5400.0,23,28,16845.0,-1
201,95.0,volvo,gas,turbo,4.0,sedan,rwd,front,109.1,188.8,...,mpfi,3.78,3.15,8.7,160.0,5300.0,19,25,19045.0,-1
202,95.0,volvo,gas,std,4.0,sedan,rwd,front,109.1,188.8,...,mpfi,3.58,2.87,8.8,134.0,5500.0,18,23,21485.0,-1
203,95.0,volvo,diesel,turbo,4.0,sedan,rwd,front,109.1,188.8,...,idi,3.01,3.40,23.0,106.0,4800.0,26,27,22470.0,-1
204,95.0,volvo,gas,turbo,4.0,sedan,rwd,front,109.1,188.8,...,mpfi,3.78,3.15,9.5,114.0,5400.0,19,25,22625.0,-1

In [20]:
import numpy as np

##### Thay thế bằng giá trị: mean, median, mode...

In [24]:
data = {
'a': [10, 9.5, 5, np.nan, 8.1, 2, 8.3, np.nan, 6, 8],
'b': [1, 8, 3, np.nan, 6, 8, 2, np.nan, 4, 8],
'c': ['fwd', '4wd', np.nan, 'fwd', 'rwd', np.nan, 'fwd', 'rwd', '4wd', 'fwd']
}
df = pd.DataFrame(data)
df

      a    b    c
0  10.0  1.0  fwd
1   9.5  8.0  4wd
2   5.0  3.0  NaN
3   NaN  NaN  fwd
4   8.1  6.0  rwd
5   2.0  8.0  NaN
6   8.3  2.0  fwd
7   NaN  NaN  rwd
8   6.0  4.0  4wd
9   8.0  8.0  fwd

In [25]:
df['a'] = df['a'].astype(float).fillna(value=df['a'].mean())
df['b'] = df['b'].astype("Int64").fillna(value=df['b'].median())
df['c'] = df['c'].fillna(value=df['c'].mode()[0])
df

         a  b    c
0  10.0000  1  fwd
1   9.5000  8  4wd
2   5.0000  3  fwd
3   7.1125  5  fwd
4   8.1000  6  rwd
5   2.0000  8  fwd
6   8.3000  2  fwd
7   7.1125  5  rwd
8   6.0000  4  4wd
9   8.0000  8  fwd

In [26]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
adult = fetch_ucirepo(id=2) 
  
# data (as pandas dataframes) 
X = adult.data.features 
y = adult.data.targets 
  
# metadata 
print(adult.metadata) 
  
# variable information 
print(adult.variables)

{'uci_id': 2, 'name': 'Adult', 'repository_url': 'https://archive.ics.uci.edu/dataset/2/adult', 'data_url': 'https://archive.ics.uci.edu/static/public/2/data.csv', 'abstract': 'Predict whether annual income of an individual exceeds $50K/yr based on census data. Also known as "Census Income" dataset. ', 'area': 'Social Science', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 48842, 'num_features': 14, 'feature_types': ['Categorical', 'Integer'], 'demographics': ['Age', 'Income', 'Education Level', 'Other', 'Race', 'Sex'], 'target_col': ['income'], 'index_col': None, 'has_missing_values': 'yes', 'missing_values_symbol': 'NaN', 'year_of_dataset_creation': 1996, 'last_updated': 'Tue Sep 24 2024', 'dataset_doi': '10.24432/C5XW20', 'creators': ['Barry Becker', 'Ronny Kohavi'], 'intro_paper': None, 'additional_info': {'summary': "Extraction was done by Barry Becker from the 1994 Census database.  A set of reasonably clean records was extracted using the following conditions: ((AAGE>16) && (AGI>100) && (AFNLWGT>1)&& (HRSWK>0))\n\nPrediction task is to determine whether a person's income is over $50,000 a year.\n", 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': 'Listing of attributes:\r\n\r\n>50K, <=50K.\r\n\r\nage: continuous.\r\nworkclass: Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked.\r\nfnlwgt: continuous.\r\neducation: Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th, 7th-8th, 12th, Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool.\r\neducation-num: continuous.\r\nmarital-status: Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse.\r\noccupation: Tech-support, Craft-repair, Other-service, Sales, Exec-managerial, Prof-specialty, Handlers-cleaners, Machine-op-inspct, Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv, Protective-serv, Armed-Forces.\r\nrelationship: Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried.\r\nrace: White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black.\r\nsex: Female, Male.\r\ncapital-gain: continuous.\r\ncapital-loss: continuous.\r\nhours-per-week: continuous.\r\nnative-country: United-States, Cambodia, England, Puerto-Rico, Canada, Germany, Outlying-US(Guam-USVI-etc), India, Japan, Greece, South, China, Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal, Ireland, France, Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary, Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago, Peru, Hong, Holand-Netherlands.', 'citation': None}}
              name     role         type      demographic  \
0              age  Feature      Integer              Age
1        workclass  Feature  Categorical           Income
2           fnlwgt  Feature      Integer             None
3        education  Feature  Categorical  Education Level
4    education-num  Feature      Integer  Education Level
5   marital-status  Feature  Categorical            Other
6       occupation  Feature  Categorical            Other
7     relationship  Feature  Categorical            Other
8             race  Feature  Categorical             Race
9              sex  Feature       Binary              Sex
10    capital-gain  Feature      Integer             None
11    capital-loss  Feature      Integer             None
12  hours-per-week  Feature      Integer             None
13  native-country  Feature  Categorical            Other
14          income   Target       Binary           Income

                                          description units missing_values
0                                                 N/A  None             no
1   Private, Self-emp-not-inc, Self-emp-inc, Feder...  None            yes
2                                                None  None             no
3    Bachelors, Some-college, 11th, HS-grad, Prof-...  None             no
4                                                None  None             no
5   Married-civ-spouse, Divorced, Never-married, S...  None             no
6   Tech-support, Craft-repair, Other-service, Sal...  None            yes
7   Wife, Own-child, Husband, Not-in-family, Other...  None             no
8   White, Asian-Pac-Islander, Amer-Indian-Eskimo,...  None             no
9                                       Female, Male.  None             no
10                                               None  None             no
11                                               None  None             no
12                                               None  None             no
13  United-States, Cambodia, England, Puerto-Rico,...  None            yes
14                                       >50K, <=50K.  None             no

In [30]:
df2 = pd.read_csv('https://archive.ics.uci.edu/static/public/2/data.csv')
df2

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,39,Private,215419,Bachelors,13,Divorced,Prof-specialty,Not-in-family,White,Female,0,0,36,United-States,<=50K.
48838,64,NaN,321403,HS-grad,9,Widowed,NaN,Other-relative,Black,Male,0,0,40,United-States,<=50K.
48839,38,Private,374983,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,50,United-States,<=50K.
48840,44,Private,83891,Bachelors,13,Divorced,Adm-clerical,Own-child,Asian-Pac-Islander,Male,5455,0,40,United-States,<=50K.
48841,35,Self-emp-inc,182148,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,60,United-States,>50K.

In [35]:
df2.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education-num',
       'marital-status', 'occupation', 'relationship', 'race', 'sex',
       'capital-gain', 'capital-loss', 'hours-per-week', 'native-country',
       'income'],
      dtype='object')

In [32]:
df2['workclass'] = df2['workclass'].astype("category").fillna(df2['workclass'].mode()[0])

In [42]:
df2.fillna(
    {
        'age': df2['age'].mode()[0],
        'workclass': df2['workclass'].mode()[0],
        'fnlwgt': df2['fnlwgt'].mode()[0],  
        'education': df2['education'].mode()[0],
        'education-num': df2['education-num'].mode()[0],
        'marital-status': df2['marital-status'].mode()[0],
        'occupation': df2['occupation'].mode()[0],
        'relationship': df2['relationship'].mode()[0],
        'race': df2['race'].mode()[0],
        'sex': df2['sex'].mode()[0],
        'capital-gain': df2['capital-gain'].mode()[0],  
        'capital-loss': df2['capital-loss'].mode()[0],
        'hours-per-week': df2['hours-per-week'].mode()[0],
        'native-country': df2['native-country'].mode()[0],
        'income': df2['income'].mode()[0]
    },
    inplace=True
)

In [43]:
df2.isna().sum()

age               0
workclass         0
fnlwgt            0
education         0
education-num     0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capital-gain      0
capital-loss      0
hours-per-week    0
native-country    0
income            0
dtype: int64

##### Thay thế bằng giá trị cố định

In [38]:
data = {
    'a': [10, 9.5, 5, np.nan, 8.1, 2, 8.3, np.nan, 6, 8],
    'b': [1, 8, 3, np.nan, 6, 8, 2, np.nan, 4, 8],
    'c': ['fwd', '4wd', np.nan, 'fwd', 'rwd', np.nan, 'fwd', 'rwd', '4wd', 'fwd']
}

df = pd.DataFrame(data)

df.fillna(
    {
        'a': -1,
        'b': -1,
        'c': 'Missing'
    },
    inplace=True
)
df

      a    b        c
0  10.0  1.0      fwd
1   9.5  8.0      4wd
2   5.0  3.0  Missing
3  -1.0 -1.0      fwd
4   8.1  6.0      rwd
5   2.0  8.0  Missing
6   8.3  2.0      fwd
7  -1.0 -1.0      rwd
8   6.0  4.0      4wd
9   8.0  8.0      fwd

##### Dung nhan du lieu bi thieu (Missingness Indicator)

In [44]:
df['a_missing'] = df['a'].isna().astype('int')
df['b_missing'] = df['b'].isna().astype('int')

##### Xóa dòng – cột

In [53]:
data = {
'a': [10, 9.5, 5, None, 8.1, 2, 8.3, pd.NA, 6, 8],
'b': [1, 8, None, 3, 6, 8, 2, 4, np.nan, 8],
'c': ['fwd', np.nan, '4wd', 'fwd', 'rwd', None, 'fwd', 'rwd', '4wd', 'fwd']
}
df = pd.DataFrame(data)
df

      a    b     c
0    10  1.0   fwd
1   9.5  8.0   NaN
2     5  NaN   4wd
3  None  3.0   fwd
4   8.1  6.0   rwd
5     2  8.0  None
6   8.3  2.0   fwd
7  <NA>  4.0   rwd
8     6  NaN   4wd
9     8  8.0   fwd

In [ ]:
df.dropna(axis=0, inplace=True) 
df

     a    b    c
0   10  1.0  fwd
4  8.1  6.0  rwd
6  8.3  2.0  fwd
9    8  8.0  fwd

#### Định dạng dữ liệu

#### Tạo và chuyển đổi đặc trưng Feature Engineering* - Transformation**

In [55]:
data = {
    'width': [10, 9.5, 5, 7, 8.1, 2, 8.3, 3, 6, 8],
    'length': [1, 8, 4.3, 3, 6.8, 8, 2, 4, 4.3, 9],
    }
df = pd.DataFrame(data)
df['width_m'] = df['width']*0.3048

In [65]:
data = {
    'a': [
    'Thống Nhất, P. Đông Hòa, Tp. HCM',
    'Đường 3/2, P. Mỹ Tho, T. Đồng Tháp',
    'Trần Hưng Đạo, P. Linh Trung, Tp. HCM',
    'Hùng Vương, P. Tân An, T. Tây Ninh',
    'Hàn Thuyên, P. Linh Xuân, Tp. HCM',
    ]
}
df = pd.DataFrame(data)
df

                                       a
0       Thống Nhất, P. Đông Hòa, Tp. HCM
1     Đường 3/2, P. Mỹ Tho, T. Đồng Tháp
2  Trần Hưng Đạo, P. Linh Trung, Tp. HCM
3     Hùng Vương, P. Tân An, T. Tây Ninh
4      Hàn Thuyên, P. Linh Xuân, Tp. HCM

In [71]:
dia_chi = df['a'].str.split(',', expand=True)
dia_chi

               0               1              2
0     Thống Nhất     P. Đông Hòa        Tp. HCM
1      Đường 3/2       P. Mỹ Tho   T. Đồng Tháp
2  Trần Hưng Đạo   P. Linh Trung        Tp. HCM
3     Hùng Vương       P. Tân An    T. Tây Ninh
4     Hàn Thuyên    P. Linh Xuân        Tp. HCM

In [73]:
dia_chi = df['a'].str.split(',', expand=True)
df['duong'] = dia_chi[0]
df['phuong_xa'] = dia_chi[1]
df['thanh_pho/tinh'] = dia_chi[2]
df

,a,duong,phuong_xa,thanh_pho/tinh
0,"Thống Nhất, P. Đông Hòa, Tp. HCM",Thống Nhất,P. Đông Hòa,Tp. HCM
1,"Đường 3/2, P. Mỹ Tho, T. Đồng Tháp",Đường 3/2,P. Mỹ Tho,T. Đồng Tháp
2,"Trần Hưng Đạo, P. Linh Trung, Tp. HCM",Trần Hưng Đạo,P. Linh Trung,Tp. HCM
3,"Hùng Vương, P. Tân An, T. Tây Ninh",Hùng Vương,P. Tân An,T. Tây Ninh
4,"Hàn Thuyên, P. Linh Xuân, Tp. HCM",Hàn Thuyên,P. Linh Xuân,Tp. HCM

In [80]:
df['a'].str.split(',',expand=False)

0         [Thống Nhất,  P. Đông Hòa,  Tp. HCM]
1       [Đường 3/2,  P. Mỹ Tho,  T. Đồng Tháp]
2    [Trần Hưng Đạo,  P. Linh Trung,  Tp. HCM]
3       [Hùng Vương,  P. Tân An,  T. Tây Ninh]
4        [Hàn Thuyên,  P. Linh Xuân,  Tp. HCM]
Name: a, dtype: object

##### Biến đổi đặc trưng

In [83]:
data = {
    'a': [10, 9.5, 5, 7, 8.1, 2, 8.3, 3, 6, 8],
    'b': [1, 8, 4.3, 3, 6.8, 8, 2, 4, 4.3, 9],
}
df = pd.DataFrame(data)

In [85]:
df['a_min_max'] = (df['a'] - df['a'].min()) / (df['a'].max() - df['a'].min())

##### Mã hóa dữ liệu dạng phân loại